### ISSUE TITLE
First public release of CloudFlare app

### ISSUE THREAD

**Issue by mattab** [bradberger/piwik-cloudflare#1]
HI @bradberger 

Thanks for the great work on the CloudFlare app.

Here are my suggestions for a public 1.0:

* [x]  Enable client side DoNotTrack detection -> we can remove this as it's IMO better to setup server side
*  [x]   Use SSL -> I don't think we need this, as it's better to leave the default tracking code (that will use SSL only when the tracked pages are SSL themselves)
 *    [x]     then you can also remove `(If you include the protocol, like https:// it will override the SSL setting)`
*   [x]  Prepend the site domain to the page title when tracking -> can you set this to 'No' by default (default in Piwik)
*   [x]     Track visitors across all sub-domains -> change the text below to: "If set to 'Yes', when one visitor visits x.domain.com and y.domain.com, they will be counted as a unique visitor."
* [x] Update app name and description in the CloudFlare UI https://github.com/BitolaCo/piwik-cloudflare/issues/2 

What do you think?

**Comment by bradberger** [comment]
This fell off my radar for a while, but was able to update everything yesterday.
