### ISSUE TITLE
Tests running on CI show an error 

### ISSUE THREAD

**Issue by mattab** [bradberger/piwik-cloudflare#4]
The goal of this issue is to make the build green on Travis CI.

Currently it fails with an error, eg. https://travis-ci.org/BitolaCo/piwik-cloudflare/builds/55898618 
```
ERROR The test with session id 7eba48b6006e40a9ac90af0079861f14 has already finished, and can't receive further commands

You can learn more at https://saucelabs.com/jobs/7eba48b6006e40a9ac90af0079861f14

For help, please check https://docs.saucelabs.com/reference/troubleshooting-common-error-messages/
```

**Comment by bradberger** [comment]
Reduced the list of browsers tested via SauceLabs to a basic list of evergreen browsers, so it's not timing out anymore.
